[package]
name = "luaf-include"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true, optional = true }
mlua = { workspace = true, optional = true }
serde.workspace = true
strum.workspace = true

[features]
default = []
logger = ["log"]
lua = ["mlua"]
